packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  gatsby-theme-material-ui@*:
    dependencies:
      gatsby-plugin-react-helmet: "*"
  gatsby-plugin-material-ui@*:
    dependencies:
      "@emotion/react": "*"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/styled": "*"
  adminjs-fastify@*:
    dependencies:
      tslib: "*"
  "@mgcrea/fastify-session-sodium-crypto@*":
    dependencies:
      "@mgcrea/fastify-session": "*"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
